[package]
name = "sample_opencv"
version = "0.1.0"
authors = ["ko-hirose"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.40"
glob = "0.3.0"
